// songs
export const FETCH_SONG_REQUSEST = 'FETCH_SONG_REQUSEST';
export const FETCH_SONG_RESPONSE = 'FETCH_SONG_RESPONSE';
export const FETCH_SONG_ERROR = 'FETCH_SONG_ERROR';

// playlist
export const FETCH_PLAYLIST_REQUSEST = 'FETCH_PLAYLIST_REQUSEST';
export const FETCH_PLAYLIST_RESPONSE = 'FETCH_PLAYLIST_RESPONSE';
export const FETCH_PLAYLIST_ERROR = 'FETCH_PLAYLIST_ERROR';

// comments
export const FETCH_COMMENTS_REQUSEST = 'FETCH_COMMENTS_REQUSEST';
export const FETCH_COMMENTS_RESPONSE = 'FETCH_COMMENTS_RESPONSE';
export const FETCH_COMMENTS_ERROR = 'FETCH_COMMENTS_ERROR';

// album
export const FETCH_ALBUM_REQUSEST = 'FETCH_ALBUM_REQUSEST';
export const FETCH_ALBUM_RESPONSE = 'FETCH_ALBUM_RESPONSE';
export const FETCH_ALBUM_ERROR = 'FETCH_ALBUM_ERROR';

// lyric
export const FETCH_LYRIC_REQUSEST = 'FETCH_LYRIC_REQUSEST';
export const FETCH_LYRIC_RESPONSE = 'FETCH_LYRIC_RESPONSE';
export const FETCH_LYRIC_ERROR = 'FETCH_LYRIC_ERROR';

// detail
export const FETCH_DETAIL_REQUSEST = 'FETCH_DETAIL_REQUSEST';
export const FETCH_DETAIL_RESPONSE = 'FETCH_DETAIL_RESPONSE';
export const FETCH_DETAIL_ERROR = 'FETCH_DETAIL_ERROR';

// recommendplaylist
export const FETCH_RECOMMENDPLAYLIST_REQUSEST = 'FETCH_RECOMMENDPLAYLIST_REQUSEST';
export const FETCH_RECOMMENDPLAYLIST_RESPONSE = 'FETCH_RECOMMENDPLAYLIST_RESPONSE';
export const FETCH_RECOMMENDPLAYLIST_ERROR = 'FETCH_RECOMMENDPLAYLIST_ERROR';

// banner
export const FETCH_BANNER_REQUSEST = 'FETCH_BANNER_REQUSEST';
export const FETCH_BANNER_RESPONSE = 'FETCH_BANNER_RESPONSE';
export const FETCH_BANNER_ERROR = 'FETCH_BANNER_ERROR';

// login
export const FETCH_LOGIN_REQUSEST = 'FETCH_LOGIN_REQUSEST';
export const FETCH_LOGIN_RESPONSE = 'FETCH_LOGIN_RESPONSE';
export const FETCH_LOGIN_ERROR = 'FETCH_LOGIN_ERROR';
