// songs
export const FETCH_SONG_REQUSEST = 'FETCH_SONG_REQUSEST';
export const FETCH_SONG_RESPONSE = 'FETCH_SONG_RESPONSE';
export const FETCH_SONG_ERROR = 'FETCH_SONG_ERROR';

// playlist
export const FETCH_PLAYLIST_REQUSEST = 'FETCH_PLAYLIST_REQUSEST';
export const FETCH_PLAYLIST_RESPONSE = 'FETCH_PLAYLIST_RESPONSE';
export const FETCH_PLAYLIST_ERROR = 'FETCH_PLAYLIST_ERROR';

// comments
export const FETCH_COMMENTS_REQUSEST = 'FETCH_COMMENTS_REQUSEST';
export const FETCH_COMMENTS_RESPONSE = 'FETCH_COMMENTS_RESPONSE';
export const FETCH_COMMENTS_ERROR = 'FETCH_COMMENTS_ERROR';
